import Styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Header from './Header.js'
import { Container } from 'react-bootstrap'
const Home = () => {
  return (
    <>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <main className={Styles.main}>

      
<Container>
        <div className={Styles.p}>
          <p>
            As a passionate gamer, I have always been fascinated by the game development and testing. Over time, I have developed a talent for identifying and reporting bugs in games. Through hours of playing and testing, I have learned to thoroughly explore every aspect of games to uncover even the hardest-to-find issues.

            This portfolio is where I share my findings with the world, including fellow developers.</p>

            <p> Gaming is a medium that has the potential to unite people and ignite creativity. Through my role in identifying and resolving bugs, I aim to make a meaningful contribution to the development of the gaming industry.
          </p>

        
          </div>
        </Container>
      </main>
    </>
  )
}

export default Home