import Head from 'next/head'
import Header from '../Header'
import Footer from '../Footer'
import Image from 'next/image'
import Tale from "../../../../public/assests/Tale.jpg"
import Styles from '@/styles/Posts.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from 'react-bootstrap'
const Apoi = () => {
  return (
    <>
      <Head>
        <title>A Tale of Plague Innocence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

      </Container>
      <Header />
      <br />
      <br />
      <main> <h1 >A Tale of Plague Innocence</h1>
        <div>
          <Image src={Tale} alt="battlefield" width={500} height={300} priority />
        </div>
       
          <h2>1. Plants and tree's branch collision detection problem: </h2>
          <p>   In Chapter 4, "The Apprentice," of A Plague Tale: Innocence, an observation was made regarding a visual glitch. While walking on a constructed wooden platform over a river, plants appeared to pass through the platform. The plants seemed to be emerging from the river below and appearing on top of the platform, despite the wooden pallets being present. This same phenomenon was observed again when a tree branch appeared to pass through a rock fence. These observations suggest a possible issue with the game's programming and should be investigated further.

          </p>
          <br />

        <div className="ratio ratio-21x9">
            <iframe src="https://www.youtube.com/embed/TP9seitsNHA" title="YouTube video" allowFullScreen></iframe>
          </div>

         
      </main >
      <Footer />
    </>
  )
}

export default Apoi