
import Head from 'next/head'
const Rotr = () => {
  return (
    <>
      <Head>
        <title>Rise Of The Tomb Raider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default Rotr