
import Head from 'next/head'
const Sotr = () => {
  return (
    <Head>
      <title>Shadow Of The Tomb Raider</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Sotr