import Header from '../Header'
import Footer from '../Footer'
import Shadow from '../../../../public/assests/Shadow.jpg'
import Image from 'next/image'
import Styles from '@/styles/Posts.module.css'
import Head from 'next/head'
const Sotr = () => {
  return (
    <>
    <Head>
      <title>Shadow Of The Tomb Raider</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
     <Header />
      <br />
      <br />
      <main className={Styles.main}> <h1 className={Styles.name}>Shadow Of The Tomb Raider</h1>
        <div className={Styles.image}>
          <Image className={Styles.image} src={Shadow} alt="Shadow Of The Tomb Raider" width={500} height={300} priority />
        </div>

        <div className={Styles.p}>
          <h2>1. Collision Detection Problem in cutscene:  </h2>
          <p>    During the "In the Shadows - Find Dominguez" objective, a cutscene featuring Lara and Jonah was triggered where they talked about the food at a street food stall. However, when Lara turned to walk away from the stall, she passed through an AI, causing a collision detection issue in the cutscene.

          </p>
          <br />
          <br />
          <div className={Styles.youtube}>
            <iframe width="960" height="560" src="https://www.youtube.com/embed/D12qucHlgUs" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
          </div>
          <br>
          </br>
          <br>
          </br>
          <hr></hr>
          <h2>2. AI Collision Detection Problem with Raised Bow:  </h2>
          <p>  A collision detection issue with AI has been observed. The issue is like the one encountered in the previous Rise OF The Tomb Raider game, and it appears that no action has been taken to address it. When attempting to raise the bow on any AI in game, the bow passes through AI’s body easily, causing a collision detection issue.
          </p>
          <br />
          <br />
          <div className={Styles.youtube}>
            <iframe width="960" height="560" src="https://www.youtube.com/embed/6C6GZBVn59w" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
          </div>
          <br>
          </br>
          <br>
          </br>
          <hr></hr>
          <h2>3. Improper implementation of AI and the object:   </h2>
          <p>  An AI programming issue has been observed in the salt farming area of the Hidden City. While exploring, an AI discovered not functioning properly. The AI's leg was in a basket with basket collision detection, and instead of putting the salt into the basket, it was placing it in the wrong location. This suggests that the AI had not been programmed correctly to fulfil its intended task.

          </p>
          <br />
          <br />
          <div className={Styles.youtube}>
            <iframe width="960" height="560" src="https://www.youtube.com/embed/1JQjb2IWPG0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
          </div>
          <br />
          <br />








        </div>
      </main>
      <Footer />
    </>
  )
}

export default Sotr